name: build and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@master
      with:
        repository: rzachary/rickeyzachary.com
        token: ${{ secrets.GITHUB_TOKEN }} # should be my personal token for github
    - name: build code
      env:
        BLOG_STATUS: prod
        JEKYLL_SRC: .
        INPUT_GEM_SRC: .
      run: |
        echo $BLOG_STATUS $JEKYLL_SRC $INPUT_GEM_SRC
        sh ./blog_deploy_helper.sh
    - name: Upload compressed blog
      uses: actions/upload-artifact@v2
      with:
        name: blog-published
        path: ./blog-published.tar.gz
  deploy:
    name: deploy blog
    runs-on: ubuntu-latest
    steps:
    - name: deploy blog to S3
      uses: actions/checkout@master
    - name: download zipped blog  
      uses: actions/download-artifact@v2
      with:
        name: blog-published
    - name: Unpack blog
      run: tar -xzvf blog-published.tar.gz ./prod
    - name: Sync S3 bucket
      uses: rzachary/s3-bucket-push@master
      with: 
        args: --acl public-read --follow-symlinks --delete
      env:
      - AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      - AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
      - AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - AWS_REGION: "us-east-1"
      - SOURCE_DIR: "prod"
      - DEST_DIR: ""
