name: build and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@master
      with:
        repository: rzachary/rickeyzachary.com
        token: ${{ secrets.GITHUB_TOKEN }} # should be my personal token for github
    - name: build code
      env:
        BLOG_STATUS: Prod
        JEKYLL_SRC: .
        INPUT_GEM_SRC: .
      run: |
        echo $BLOG_STATUS $JEKYLL_SRC $INPUT_GEM_SRC
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy artifact
      run: echo Hello World!
