name: build and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@master
      with:
        repository: rzachary/rickeyzachary.com
        token: ${{ secrets.GITHUB_TOKEN }} # should be my personal token for github
    - name: setup ruby and install dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: Build the blog
      run: |
        bundle exec jekyll clean --destination ./prod
        bundle exec jekyll build --destination ./prod
        tar -czvf blog-published.tar.gz ./prod
    - name: Upload compressed blog
      uses: actions/upload-artifact@v2
      with:
        name: blog-published
        path: ./blog-published.tar.gz
  deploy:
    name: deploy blog
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: deploy blog to S3
      run: pwd
    - name: download zipped blog
      uses: actions/download-artifact@v2
      with:
        name: blog-published
        path: ${{ github.workspace }}
    - name: Unpack blog
      run: |
        ls ${{ github.workspace }}
        file blog-published.tar.gz
        tar -zxvf ${{ github.workspace }}/blog-published.tar.gz 
        ls ${{ github.workspace }}/prod/
    - name: Sync S3 bucket
      uses: rzachary/s3-bucket-push@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"
        SOURCE_DIR: "prod"
        DEST_DIR: "./"
