name: build and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@master
    - name: build code
      run: echo Hello World!
  deploy:
    name: deploy
    runs-on: unbuntu-latest
    steps:
    - name: deploy artifact
      run: echo Hwllo World!
